### PR TITLE
Removed the Favorite Location feature from the Maps Service. 

### PR DESCRIPTION
**Pull request by donnylaplume**
No known bugs, but I did also fix one in the maps database to validate if an address exists but only the address is entered.

### CODE REVIEW

**Review by bdeng27 — APPROVED** [review]
Looks good.  I think.  Probably.

**Review by J-H-Tran — APPROVED** [review]
Great deletion work

**Comment by ssauc** [comment]
looks good

**Review by ssauc — APPROVED** [review]
Looks good

**Pull request merged**
